data = {
    'cap': {
        'shape': {
            'flat': 'xnegative',
            'bell': 'xnegative',
            'convex': 'xnegative',
            'conical': 'xnegative'},
        'surface': {
            'scaly': 'xnegative',
            'smooth': 'xnegative',
            'fibrous': 'xnegative'},
        'color': {
            'white': 'xnegative',
            'brown': 'xnegative',
            'pink': 'xnegative'}},
    'bruises': {
        'presence': {
            'visible': 'xnegative'}},
    'gills': {
        'spacing': {
            'close': 'xnegative',
            'crowded': 'xnegative'}},
    'stalk_root': {
        'shape': {
            'bulbous': 'xnegative',
            'club': 'xnegative',
            'equal': 'xnegative'}},
    'stalk_above_ring': {
        'color': {
            'white': 'xnegative',
            'red': 'xnegative'}},
    'stalk_below_ring': {
        'color': {
            'white': 'xnegative',
            'red': 'xnegative'}},
    'rings': {
        'number': {
            'none': 'xnegative',
            'one': 'xnegative',
            'two': 'xnegative'}},
    'veil': {
        'color': {
            'brown': 'xnegative',
            'orange': 'xnegative',
            'yellow': 'xnegative',
            'white': 'xnegative'}}
}
